import { execFile } from "node:child_process";
import { existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import type { ExtensionAPI } from "@oh-my-pi/pi-coding-agent";

const REVIEWER_MARKER = "CRITICAL_REVIEWER_READ_ONLY_V1";
const INLINE_ISOLATED_MARKER = "CRITICAL_REVIEWER_INLINE_ISOLATED_V1";
const ISOLATED_TOOLS: Record<string, true> = { yield: true };
const READ_ONLY_TOOLS: Record<string, true> = {
	read: true,
	grep: true,
	glob: true,
	lsp: true,
	ast_grep: true,
	yield: true,
};

const TASK_TOOL = "task";
const BLOCK_PREFIX = "critical-review dispatch";

/** Every reviewer seat runs a `review-*` agent, so a Task item naming one is a protected item. */
export const REVIEWER_AGENT_PREFIX = "review-";
/** First line of the shared machine marker the lead passes as the batch `context`. */
export const DISPATCH_MARKER_HEADER = "CRITICAL_REVIEW_DISPATCH_V1";
/** First token of every resolver-generated reviewer task body. */
export const RESOLVER_RECEIPT_HEADER = "CRITICAL_REVIEW_RESOLVER_RECEIPT_V1";

// The entire marker, not a prefix: `$` in a non-multiline JS pattern only matches end of input, so a
// trailing newline, leading whitespace, or any surrounding prose is a mismatch and fails closed.
const MARKER_PATTERN =
	/^CRITICAL_REVIEW_DISPATCH_V1\nenvelope_path=(\/[^\n]+)\nenvelope_sha256=([0-9a-f]{64})$/u;

/**
 * Fixed sibling of this extension, resolved from this module's own realpath, so no caller can point
 * the gate at a different verifier. The skill half and this file are deployed side by side, which
 * makes the relative path correct both in the dotfiles checkout and under `~/.omp/agent`.
 */
export const VERIFIER_SCRIPT = fileURLToPath(
	new URL("../skills/critical-review/lrhe/review_dispatch.py", import.meta.url),
);
/** The skill's own interpreter, used when present because the verifier needs the skill's PyYAML. */
export const VERIFIER_PYTHON = fileURLToPath(
	new URL("../skills/critical-review/lrhe/.venv/bin/python", import.meta.url),
);
export const VERIFIER_TIMEOUT_MS = 30_000;
const VERIFIER_MAX_OUTPUT_BYTES = 4 * 1024 * 1024;
const VERIFIER_REASON_LIMIT = 500;

export interface DispatchMarker {
	envelopePath: string;
	envelopeSha256: string;
}

export interface CanonicalTaskInput {
	context: string;
	/** The task tool's required intent field; generated by the resolver, compared byte for byte. */
	i: string;
	tasks: Record<string, unknown>[];
}

/** Resolves the verifier's stdout on a clean exit; rejects on any other outcome. */
export type VerifyTask = (marker: DispatchMarker) => Promise<string>;

export type TaskDecision =
	| { block: true; reason: string }
	| { input: CanonicalTaskInput }
	| undefined;

function isPlainObject(value: unknown): value is Record<string, unknown> {
	return typeof value === "object" && value !== null && !Array.isArray(value);
}

function blocked(reason: string): { block: true; reason: string } {
	return { block: true, reason: `${BLOCK_PREFIX}: ${reason}` };
}

/** Structural JSON equality: array order matters, object key order does not, extra keys never do. */
export function deepEqual(left: unknown, right: unknown): boolean {
	if (left === right) return true;
	if (Array.isArray(left) || Array.isArray(right)) {
		if (
			!Array.isArray(left) ||
			!Array.isArray(right) ||
			left.length !== right.length
		)
			return false;
		return left.every((value, index) => deepEqual(value, right[index]));
	}
	if (!isPlainObject(left) || !isPlainObject(right)) return false;
	const keys = Object.keys(left);
	if (keys.length !== Object.keys(right).length) return false;
	return keys.every(
		(key) => Object.hasOwn(right, key) && deepEqual(left[key], right[key]),
	);
}

export function isReviewerItem(item: unknown): item is Record<string, unknown> {
	return (
		isPlainObject(item) &&
		typeof item.agent === "string" &&
		item.agent.startsWith(REVIEWER_AGENT_PREFIX)
	);
}

// The resolver emits each seat as exactly `{agent, task}`; a stray `name`, `effort`, or output
// schema means the payload did not come from the resolver and must not reach the task tool.
function isCanonicalTaskItem(item: unknown): item is Record<string, unknown> {
	if (!isReviewerItem(item)) return false;
	const keys = Object.keys(item).sort();
	if (keys.length !== 2 || keys[0] !== "agent" || keys[1] !== "task")
		return false;
	return (
		typeof item.task === "string" &&
		item.task.startsWith(RESOLVER_RECEIPT_HEADER)
	);
}

export function parseDispatchMarker(context: unknown): DispatchMarker | null {
	if (typeof context !== "string") return null;
	const match = MARKER_PATTERN.exec(context);
	const envelopePath = match?.[1];
	const envelopeSha256 = match?.[2];
	if (!envelopePath || !envelopeSha256) return null;
	return { envelopePath, envelopeSha256 };
}


/**
 * Accepts only the exact canonical batch Task shape `{context, i, tasks}`.
 * A focused review is a one-item batch; councils use the same shape without
 * creating a second single-reviewer convention.
 */
export function parseVerifierOutput(
	stdout: unknown,
): CanonicalTaskInput | null {
	if (typeof stdout !== "string") return null;
	let parsed: unknown;
	try {
		parsed = JSON.parse(stdout);
	} catch {
		return null;
	}
	if (!isPlainObject(parsed)) return null;
	const outerKeys = Object.keys(parsed);
	if (outerKeys.length !== 1 || outerKeys[0] !== "task_input") return null;
	const taskInput = parsed.task_input;
	if (!isPlainObject(taskInput)) return null;
	const innerKeys = Object.keys(taskInput).sort();
	if (
		innerKeys.length !== 3 ||
		innerKeys[0] !== "context" ||
		innerKeys[1] !== "i" ||
		innerKeys[2] !== "tasks"
	)
		return null;
	const { context, i, tasks } = taskInput;
	if (typeof context !== "string" || !parseDispatchMarker(context)) return null;
	if (typeof i !== "string" || i.trim().length === 0) return null;
	if (!Array.isArray(tasks) || tasks.length < 1) return null;
	if (!tasks.every(isCanonicalTaskItem)) return null;
	return { context, i, tasks };
}

function verifierFailureReason(error: unknown, stderr?: string): string {
	const refusal = (stderr ?? "")
		.trim()
		.split("\n")[0]
		?.slice(0, VERIFIER_REASON_LIMIT);
	if (!isPlainObject(error))
		return `verifier could not be run: ${String(error)}`;
	if (
		error.killed === true ||
		(typeof error.signal === "string" && error.signal.length > 0)
	) {
		return `verifier exceeded its ${VERIFIER_TIMEOUT_MS}ms budget`;
	}
	const message =
		typeof error.message === "string" ? error.message : String(error);
	const detail = refusal || message.slice(0, VERIFIER_REASON_LIMIT);
	if (typeof error.code === "number")
		return `verifier exited with code ${error.code}: ${detail}`;
	return `verifier could not be run: ${detail}`;
}

/**
 * Runs the fixed sibling verifier with an argv array — never a shell — under a hard timeout that
 * SIGKILLs the child rather than leaving the gate waiting on it. The verifier reaches PyYAML through
 * the skill's qualification module, which only re-execs into the virtualenv as `__main__`, so the
 * skill's own interpreter is preferred over a bare `python3` that may not have it.
 */
export const verifyTaskViaSkill: VerifyTask = (marker) =>
	new Promise<string>((resolve, reject) => {
		execFile(
			existsSync(VERIFIER_PYTHON) ? VERIFIER_PYTHON : "python3",
			[
				VERIFIER_SCRIPT,
				"verify-task",
				"--envelope",
				marker.envelopePath,
				"--sha256",
				marker.envelopeSha256,
			],
			{
				encoding: "utf8",
				killSignal: "SIGKILL",
				maxBuffer: VERIFIER_MAX_OUTPUT_BYTES,
				shell: false,
				timeout: VERIFIER_TIMEOUT_MS,
				windowsHide: true,
			},
			(error, stdout, stderr) => {
				if (error) reject(new Error(verifierFailureReason(error, stderr)));
				else resolve(stdout);
			},
		);
	});

/**
 * Gate for parent `task` calls. Reviewer batches must contain only reviewer
 * items and carry the exact context marker. A single reviewer uses the same
 * batch shape with one item. Calls with no reviewer pass.
 */
export async function evaluateTaskDispatch(
	rawInput: unknown,
	verify: VerifyTask = verifyTaskViaSkill,
): Promise<TaskDecision> {
	if (!isPlainObject(rawInput)) return undefined;
	const tasks = rawInput.tasks;
	if (!Array.isArray(tasks)) {
		if (!isReviewerItem(rawInput)) return undefined;
		return blocked(
			"reviewers must use the verifier-generated batch Task shape.",
		);
	}
	if (!tasks.some(isReviewerItem)) return undefined;
	if (!tasks.every(isReviewerItem)) {
		return blocked(
			`a batch containing a ${REVIEWER_AGENT_PREFIX}* agent must contain only reviewer items.`,
		);
	}
	const marker = parseDispatchMarker(rawInput.context);
	if (!marker) {
		return blocked(
			`the task context is not an exact ${DISPATCH_MARKER_HEADER} marker; dispatch reviewers through review_dispatch.py.`,
		);
	}

	let stdout: string;
	try {
		stdout = await verify(marker);
	} catch (error) {
		return blocked(
			error instanceof Error ? error.message : verifierFailureReason(error),
		);
	}
	const canonical = parseVerifierOutput(stdout);
	if (!canonical) {
		return blocked("the verifier did not emit a strict task_input object.");
	}
	if (!deepEqual(rawInput, canonical)) {
		return blocked(
			"this call does not match the verifier-approved canonical dispatch.",
		);
	}
	return { input: canonical };
}

/**
 * Enforces the reviewer boundary even when OMP injects coordination tools into subagents, and gates
 * the parent side so a reviewer seat can only be spawned from a verified dispatch envelope. The
 * loader passes only `pi`; `verify` exists so tests can drive the gate without spawning the skill.
 */
export default function criticalReviewPolicy(
	pi: ExtensionAPI,
	verify: VerifyTask = verifyTaskViaSkill,
): void {
	pi.on("tool_call", async (event, ctx) => {
		const prompt = ctx.getSystemPrompt();
		const isolated = prompt.some((part) =>
			part.includes(INLINE_ISOLATED_MARKER),
		);
		const isCriticalReviewer =
			isolated || prompt.some((part) => part.includes(REVIEWER_MARKER));
		if (isCriticalReviewer) {
			const allowedTools = isolated ? ISOLATED_TOOLS : READ_ONLY_TOOLS;
			if (allowedTools[event.toolName]) return;
			return {
				block: true,
				reason: `Critical reviewers are read-only and isolated; ${event.toolName} is not permitted.`,
			};
		}

		if (event.toolName !== TASK_TOOL) return;
		const decision = await evaluateTaskDispatch(event.input, verify);
		if (!decision || "block" in decision) return decision;
		return { input: decision.input };
	});
}
